# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

dist: trusty
sudo: false

cache:
  apt: true
  directories:
    - ${HOME}/.m2
    - ${HOME}/R

env:
  global:
    # Interpreters does not required by zeppelin-server integration tests
    - INTERPRETERS='!hbase,!pig,!jdbc,!file,!flink,!ignite,!kylin,!lens,!cassandra,!elasticsearch,!bigquery,!alluxio,!scio,!livy,!groovy,!sap'

matrix:
  include:
    # Test License compliance using RAT tool
    - jdk: "oraclejdk8"
      env:
        - DSC="Test License compliance using RAT tool"
        - BUILD_PLUGINS="false"
        - SCALA_VER="2.11"
        - PROFILE="-Prat"
        - BUILD_FLAG="clean"
        - TEST_FLAG="org.apache.rat:apache-rat-plugin:check"
        - TEST_PROJECTS=""

    # Run e2e tests (in zeppelin-web)
    - jdk: "oraclejdk8"
      addons:
        chrome: stable
        apt:
          packages:
            - python
            - python-dev
            - python-pip
            - python-virtualenv
      env:
        - DSC="Run e2e tests (in zeppelin-web)"
        - BUILD_PLUGINS="false"
        - CI="true"
        - WEB_E2E="true"
        - PYTHON="2"
        - SCALA_VER="2.11"
        - SPARK_VER="2.1.0"
        - HADOOP_VER="2.6"
        - PROFILE="-Phadoop2 -Pscala-2.11" BUILD_FLAG="package -DskipTests -DskipRat"
        - TEST_FLAG="verify -DskipRat"
        - MODULES="-pl ${INTERPRETERS}"
        - TEST_MODULES="-pl zeppelin-web"
        - TEST_PROJECTS="-Pweb-e2e"

before_install:
  - echo "MAVEN_OPTS='-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms1024M -Xmx2048M -XX:MaxPermSize=1024m -XX:-UseGCOverheadLimit -Dorg.slf4j.simpleLogger.defaultLogLevel=info'" >> ~/.mavenrc
  - travis_wait 30 travis_retry ./testing/install_external_dependencies.sh
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1024x16"
  - export DISPLAY=:99.0
  - source .environ
  - rm .environ

install:
  - echo "mvn $BUILD_FLAG $MODULES $PROFILE -B"
  - mvn $BUILD_FLAG $MODULES $PROFILE -B
  - if [ $BUILD_PLUGINS == "true" ]; then echo "mvn clean package -pl zeppelin-plugins -amd -B"; mvn clean package -pl zeppelin-plugins -amd -B; fi

before_script:
  - if [[ -n $SPARK_VER ]]; then travis_retry ./testing/downloadSpark.sh $SPARK_VER $HADOOP_VER; fi
  - if [[ -n $SPARK_VER ]]; then export SPARK_HOME=`pwd`/spark-$SPARK_VER-bin-hadoop$HADOOP_VER; fi
  - if [[ -n $SPARK_VER ]]; then echo "export SPARK_HOME=`pwd`/spark-$SPARK_VER-bin-hadoop$HADOOP_VER" > conf/zeppelin-env.sh; fi
  - if [[ -n $LIVY_VER ]]; then ./testing/downloadLivy.sh $LIVY_VER; fi
  - if [[ -n $LIVY_VER ]]; then export LIVY_HOME=`pwd`/livy-$LIVY_VER-bin; fi
  - echo "export ZEPPELIN_HELIUM_REGISTRY=helium" >> conf/zeppelin-env.sh
  - echo "export SPARK_PRINT_LAUNCH_COMMAND=true" >> conf/zeppelin-env.sh
  - tail conf/zeppelin-env.sh

script:
  - if [[ -n $TEST_MODULES ]]; then export MODULES="${TEST_MODULES}"; fi
  - echo "mvn -T 1C $TEST_FLAG $MODULES $PROFILE -B $TEST_PROJECTS"
  - mvn -T 1C $TEST_FLAG $MODULES $PROFILE -B $TEST_PROJECTS

after_failure:
  - find . -name rat.txt | xargs cat
  - cat logs/*
  - cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.log
  - cat zeppelin-distribution/target/zeppelin-*-SNAPSHOT/zeppelin-*-SNAPSHOT/logs/zeppelin*.out
  - cat zeppelin-web/npm-debug.log
  - cat spark-*/logs/*
  - cat livy/target/tmp/*/output.log
  - cat livy/target/tmp/livy-int-test/*/output.log
  - ls -R livy/target/tmp/livy-int-test/MiniYarnMain/target/org.apache.livy.test.framework.MiniYarnMain/*
  - cat livy/target/tmp/livy-int-test/MiniYarnMain/target/org.apache.livy.test.framework.MiniYarnMain/*/*/*/stdout
  - cat livy/target/tmp/livy-int-test/MiniYarnMain/target/org.apache.livy.test.framework.MiniYarnMain/*/*/*/stderr
